### ISSUE TITLE
Add link to GitHub repo on NPM package listing

### ISSUE THREAD

**Issue by edmorley** [DrBoolean/immutable-ext#10]
Currently the package listing doesn't link to the repo:
https://www.npmjs.com/package/immutable-ext

I'm presuming those links come from the `package.json` fields?
https://docs.npmjs.com/files/package.json#repository

**Comment by wking-io** [comment]
@DrBoolean I have a PR to update this! #13

**Comment by DrBoolean** [comment]
Thanks! @wking-io
