### ISSUE TITLE
Babel not transpiling.

### ISSUE THREAD

**Issue by niksosf** [DrBoolean/immutable-ext#11]
Hi there, first off thanks for this great little lib and all the videos!

I am running into a compilation error while trying to minify immutable-ext related code
```
Failed to minify the code from this file:

 	./node_modules/immutable-ext/index.js:2```

Here are the simple steps to reproduce it

npm i create-react-app
create-react-app demo2
cd demo2
yarn build
yarn add immutable immutable-ext

then add 

```
import { List } from 'immutable-ext'
List(['Hey', 'Ho', 'Lets Go!'])
```
to index.js

yarn build

Cheers!

**Comment by DrBoolean** [comment]
Hi @niksosf I think it probably has to do with not compiling down first. I just accepted a pr a do that. I'll republish now
