### ISSUE TITLE
Installing this library does not bring in immutablejs dependency

### ISSUE THREAD

**Issue by amite** [DrBoolean/immutable-ext#4]
When I run `npm i immutable-ext`

**Expected Behaviour**

```
composable-functional-javascript@1.0.0 /Users/amiterandole/Documents/current/javascript/composable-functional-javascript
└── immutable-ext@1.0.8
```

**Actual Behaviour**

```
composable-functional-javascript@1.0.0 /Users/amiterandole/Documents/current/javascript/composable-functional-javascript
├── UNMET PEER DEPENDENCY immutable@*
└── immutable-ext@1.0.8
```

Currently I manually install `immutable` first and then the install works

**Comment by eliperelman** [comment]
@amite peerDependencies are not automatically installed starting with npm 3 I believe. It is expected behavior for you to install these yourself, but it should probably be included in the README to also install immutable so it is clearer.

**Comment by DrBoolean** [comment]
Yep! totally the desired behavior
